"""Persist deterministic preprocessing runs and searchable projections."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision='0002_document_preprocessing'
down_revision='0001_database_foundation'
branch_labels=None
depends_on=None

def upgrade():
    op.create_table('document_processing_runs',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('organization_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('organizations.id',ondelete='CASCADE'),nullable=False),sa.Column('document_id',postgresql.UUID(as_uuid=True),nullable=False),sa.Column('processing_job_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('processing_jobs.id',ondelete='CASCADE'),nullable=False),sa.Column('attempt_number',sa.Integer(),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('schema_version',sa.String(50),nullable=False),sa.Column('processor_version',sa.String(100),nullable=False),sa.Column('original_document_checksum',sa.String(64),nullable=False),sa.Column('page_count',sa.Integer()),sa.Column('inspection',postgresql.JSONB()),sa.Column('warnings',postgresql.JSONB()),sa.Column('result_storage_key',sa.Text()),sa.Column('result_sha256_checksum',sa.String(64)),sa.Column('error_code',sa.String(100)),sa.Column('error_message',sa.Text()),sa.Column('started_at',sa.DateTime(timezone=True),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(['organization_id','document_id'],['documents.organization_id','documents.id'],ondelete='CASCADE'),sa.UniqueConstraint('processing_job_id','attempt_number',name='uq_runs_job_attempt'),sa.CheckConstraint("status IN ('running','completed','failed')",name='ck_document_processing_runs_status_allowed'))
    op.create_table('document_pages',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('processing_run_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('document_processing_runs.id',ondelete='CASCADE'),nullable=False),sa.Column('organization_id',postgresql.UUID(as_uuid=True),nullable=False),sa.Column('page_number',sa.Integer(),nullable=False),sa.Column('width_points',sa.Float(),nullable=False),sa.Column('height_points',sa.Float(),nullable=False),sa.Column('rotation_degrees',sa.Integer(),nullable=False),sa.Column('native_plain_text',sa.Text(),nullable=False),sa.Column('native_character_count',sa.Integer(),nullable=False),sa.Column('native_word_count',sa.Integer(),nullable=False),sa.Column('ocr_status',sa.String(32),nullable=False),sa.Column('ocr_plain_text',sa.Text()),sa.Column('quality',postgresql.JSONB(),nullable=False),sa.Column('render_storage_key',sa.Text(),nullable=False),sa.Column('render_media_type',sa.String(32),nullable=False),sa.Column('render_pixel_width',sa.Integer(),nullable=False),sa.Column('render_pixel_height',sa.Integer(),nullable=False),sa.Column('render_dpi',sa.Integer(),nullable=False),sa.Column('render_checksum',sa.String(64),nullable=False),sa.Column('warnings',postgresql.JSONB()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('processing_run_id','page_number',name='uq_pages_run_number'))
    op.create_table('document_blocks',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('processing_run_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('document_processing_runs.id',ondelete='CASCADE'),nullable=False),sa.Column('document_page_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('document_pages.id',ondelete='CASCADE'),nullable=False),sa.Column('organization_id',postgresql.UUID(as_uuid=True),nullable=False),sa.Column('external_block_id',sa.String(128),nullable=False),sa.Column('representation',sa.String(32),nullable=False),sa.Column('extraction_source',sa.String(32),nullable=False),sa.Column('block_type',sa.String(32)),sa.Column('reading_order',sa.Integer(),nullable=False),sa.Column('text',sa.Text()),sa.Column('x0',sa.Float(),nullable=False),sa.Column('y0',sa.Float(),nullable=False),sa.Column('x1',sa.Float(),nullable=False),sa.Column('y1',sa.Float(),nullable=False),sa.Column('font',postgresql.JSONB()),sa.Column('ocr_confidence',sa.Float()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('processing_run_id','external_block_id',name='uq_blocks_run_external_id'))
    op.create_table('document_tables',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('processing_run_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('document_processing_runs.id',ondelete='CASCADE'),nullable=False),sa.Column('document_page_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('document_pages.id',ondelete='CASCADE'),nullable=False),sa.Column('organization_id',postgresql.UUID(as_uuid=True),nullable=False),sa.Column('external_table_id',sa.String(128),nullable=False),sa.Column('table_index',sa.Integer(),nullable=False),sa.Column('x0',sa.Float(),nullable=False),sa.Column('y0',sa.Float(),nullable=False),sa.Column('x1',sa.Float(),nullable=False),sa.Column('y1',sa.Float(),nullable=False),sa.Column('rows',postgresql.JSONB(),nullable=False),sa.Column('warnings',postgresql.JSONB()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('processing_run_id','external_table_id',name='uq_tables_run_external_id'),sa.UniqueConstraint('document_page_id','table_index',name='uq_tables_page_index'))

def downgrade():
    op.drop_table('document_tables'); op.drop_table('document_blocks'); op.drop_table('document_pages'); op.drop_table('document_processing_runs')
