import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { UploadCloud, ChevronRight, FileText, Clock3, CheckCircle2, AlertTriangle, XCircle, LoaderCircle, Search, CircleHelp } from 'lucide-react';
import type { MockDocument, Status } from './types';
import './styles.css';
import { MaximorApi, apiBaseUrl, type ApiDocument, type Pipeline } from './api';

const labels:Record<Status,string>={processing:'Processing',completed:'Completed',review_required:'Review required',failed_validation:'Failed validation',queued:'Queued'};
const icons:Record<Status,typeof CheckCircle2>={processing:LoaderCircle,completed:CheckCircle2,review_required:AlertTriangle,failed_validation:XCircle,queued:Clock3};
function StatusPill({status}:{status:Status}){const Icon=icons[status];return <span className={`status ${status}`}><Icon size={14}/>{labels[status]}</span>}
function App(){
 const [org,setOrg]=useState(import.meta.env.VITE_MAXIMOR_ORGANIZATION_ID||''); const [docs,setDocs]=useState<MockDocument[]>([]); const [selected,setSelected]=useState(''); const [filter,setFilter]=useState<'all'|Status>('all'); const [tab,setTab]=useState('Pipeline'); const [query,setQuery]=useState(''); const [live,setLive]=useState(false); const [error,setError]=useState(''); const [pipelines,setPipelines]=useState<Record<string,Pipeline>>({});
 const client=useMemo(()=>new MaximorApi(apiBaseUrl),[]);
 const refresh=()=>{if(!org){setLive(false);setDocs([]);setSelected('');return} client.listDocuments(org).then(({documents})=>{setDocs(documents.map(toMock));setSelected(s=>documents.some(d=>d.document_id===s)?s:(documents[0]?.document_id||''));setLive(true);setError('')}).catch(()=>{setLive(false);setDocs([]);setSelected('');setError('Backend unavailable — connect the API to load documents.')})};
 useEffect(()=>{refresh()},[org]);
 useEffect(()=>{if(!org||!live)return;let timer:number;let stopped=false;const active=(p:Pipeline)=>{const states=[p.preprocessing?.status,p.document_analysis?.status,p.term_applicability?.status,p.normalization?.status];return states.some(s=>s==='queued'||s==='running')||p.sku_mapping?.candidates?.some((c:any)=>c.status==='queued'||c.status==='running')};const poll=async()=>{const results=await Promise.all(docs.map(d=>client.pipeline(org,d.id).catch(()=>null)));if(stopped)return;const valid=results.filter((p):p is Pipeline=>p!==null);if(valid.length)setPipelines(x=>{const next={...x};valid.forEach(p=>{next[p.document_id]=p});return next});if(valid.some(active))timer=window.setTimeout(poll,2000)};poll();return()=>{stopped=true;window.clearTimeout(timer)}},[org,live,docs.length]);
 const doc=docs.find(d=>d.id===selected)??docs[0];
 const counts=useMemo(()=>({all:docs.length,processing:docs.filter(d=>d.status==='processing').length,completed:docs.filter(d=>d.status==='completed').length,review_required:docs.filter(d=>d.status==='review_required').length,failed_validation:docs.filter(d=>d.status==='failed_validation').length}),[docs]);
 const visible=docs.filter(d=>(filter==='all'||d.status===filter)&&`${d.filename} ${d.customer}`.toLowerCase().includes(query.toLowerCase()));
 function addFiles(files:FileList|null){if(!files)return;const additions=Array.from(files).map((f,i):MockDocument=>({id:`mock-${Date.now()}-${i}`,filename:f.name,customer:'Pending identification',uploaded:'Just now',status:'queued',stage:'Queued',itemCount:0,pages:0,stages:['Upload','PDF preprocessing','Document analysis','SKU mapping','Term enrichment','Normalization / finalization'].map(name=>({name,state:name==='Upload'?'completed':'queued',duration:'—'})),lineItems:[],evidence:[],note:'Mock upload only — backend wiring is intentionally pending.'}));setDocs(d=>[...additions,...d]);if(additions[0])setSelected(additions[0].id)}
 return <div className="app-shell"><aside><div className="brand"><div className="brand-mark">M</div><div><strong>MAXIMOR</strong><small>OPERATIONS CONSOLE</small></div></div><nav><button className="nav-active"><FileText size={17}/>Order forms</button><button><Clock3 size={17}/>Pipeline activity</button><button><CircleHelp size={17}/>Review queue <span className="nav-count">2</span></button></nav><div className="aside-foot"><div className="health-dot"/>{live?'Live API connected':'Mock mode active'}<br/><small>{live?apiBaseUrl:'Enter an organization to connect'}</small></div></aside>
 <main><header><div><p className="eyebrow">OPERATIONS / DOCUMENT PIPELINE</p><h1>Order forms</h1></div><div className="header-actions"><label className="org-input">Organization ID<input value={org} onChange={e=>setOrg(e.target.value.trim())} placeholder="Paste UUID" aria-label="Organization ID"/></label><label className="batch-select">Batch <select defaultValue="September order forms"><option>September order forms</option></select></label><label className="upload-button"><UploadCloud size={17}/>Upload documents<input type="file" multiple accept=".pdf" onChange={async e=>{if(!org){setError('Enter an organization ID before uploading.');return}for(const file of Array.from(e.target.files||[])){try{await client.upload(org,file)}catch{setError(`Upload failed for ${file.name}.`)}}refresh()}}/></label></div></header>{error&&<div className="api-notice">{error}</div>}
 <section className="summary-grid">{[['Total documents',counts.all,'all'],['Processing',counts.processing,'processing'],['Completed',counts.completed,'completed'],['Review required',counts.review_required,'review_required'],['Failed validation',counts.failed_validation,'failed_validation']].map(([name,count,key])=><button key={String(key)} className={`summary-card ${filter===key?'summary-selected':''}`} onClick={()=>setFilter(key as any)}><span>{name}</span><strong>{count}</strong></button>)}</section>
 <div className="workspace"><section className="documents-panel"><div className="panel-heading"><div><h2>Documents</h2><span className="muted">6 in this batch · sample UI data</span></div><div className="search"><Search size={15}/><input aria-label="Filter documents" placeholder="Filter documents" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="filter-tabs">{[['all','All'],['processing','Processing'],['completed','Completed'],['review_required','Review required'],['failed_validation','Failed']].map(([key,name])=><button className={filter===key?'active':''} onClick={()=>setFilter(key as any)} key={key}>{name}<b>{counts[key as keyof typeof counts]}</b></button>)}</div><div className="table-wrap"><table><thead><tr><th>Filename</th><th>Customer</th><th>Uploaded</th><th>Current stage</th><th>Status</th><th>Items</th><th></th></tr></thead><tbody>{visible.map(d=><tr className={selected===d.id?'row-selected':''} onClick={()=>{setSelected(d.id);setTab('Pipeline')}} key={d.id}><td><div className="file-cell"><span className="file-icon"><FileText size={15}/></span><strong>{d.filename}</strong></div></td><td>{d.customer}</td><td className="muted">{d.uploaded}</td><td>{d.stage}</td><td><StatusPill status={d.status}/></td><td>{d.itemCount||'—'}</td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div><div className="drop-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(e.dataTransfer.files)}}><UploadCloud size={22}/><div><strong>Drop order-form PDFs here</strong><span>Select multiple files · mock behavior only</span></div><label className="text-button">Choose files<input type="file" multiple accept=".pdf" onChange={e=>addFiles(e.target.files)}/></label></div></section>
 {doc?<Detail doc={doc} tab={tab} setTab={setTab} pipeline={pipelines[doc.id]}/>:<section className="detail-panel"><div className="empty-state"><FileText size={20}/><strong>No documents yet</strong><span>Upload a PDF to begin tracking the pipeline.</span></div></section>}</div></main></div>}
function toMock(d:ApiDocument):MockDocument{const raw=d.business_status||d.status;const status:Status=raw==='processing'?'processing':raw==='review_required'?'review_required':raw==='failed'||raw==='failed_validation'?'failed_validation':raw==='queued'?'queued':'completed';return {id:d.document_id,filename:d.original_filename,customer:'Tenant document',uploaded:new Date(d.created_at).toLocaleString(),status,stage:d.current_stage,itemCount:d.item_count||0,pages:0,stages:[],lineItems:[],evidence:[],note:d.review_issue_count?`${d.review_issue_count} review issue(s) require attention.`:undefined}}
function Detail({doc,tab,setTab,pipeline}:{doc:MockDocument;tab:string;setTab:(x:string)=>void;pipeline?:Pipeline}){return <section className="detail-panel"><div className="detail-head"><div><p className="eyebrow">SELECTED DOCUMENT</p><h2>{doc.filename}</h2><p className="customer">{doc.customer} <span>·</span> uploaded {doc.uploaded.toLowerCase()}</p></div><StatusPill status={doc.status}/></div><div className="detail-meta"><span><small>Pages</small>{doc.pages||'—'}</span><span><small>Line items</small>{doc.itemCount||'—'}</span><span><small>Environment</small>{pipeline?'Live API':'Mock data'}</span></div><div className="segmented">{['Pipeline','Extracted result','Evidence'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='Pipeline'?<Pipeline doc={doc} pipeline={pipeline}/>:tab==='Extracted result'?<Result doc={doc} pipeline={pipeline}/>:<Evidence doc={doc}/>}</section>}
function Pipeline({doc,pipeline}:{doc:MockDocument;pipeline?:Pipeline}){const state=(run:any):string=>{const s=run?.status;return s==='completed'?'completed':s==='review_required'||s==='failed_validation'?'review':s==='failed'?'failed':s==='running'?'running':'queued'};const stages=doc.stages.length?doc.stages:[{name:'Upload',state:'completed',duration:'—'},{name:'PDF preprocessing',state:state(pipeline?.preprocessing),duration:'—'},{name:'Document analysis',state:state(pipeline?.document_analysis),duration:'—'},{name:'SKU mapping',state:pipeline&&pipeline.sku_mapping.completed===Number(pipeline.sku_mapping.total)&&Number(pipeline.sku_mapping.total)>0?'completed':'running',duration:'—',detail:pipeline?`${pipeline.sku_mapping.completed} of ${pipeline.sku_mapping.total} candidates mapped`:undefined},{name:'Term enrichment',state:state(pipeline?.term_applicability),duration:'—'},{name:'Normalization / finalization',state:state(pipeline?.normalization),duration:'—'}] as any;return <div className="pipeline"><div className="callout"><span className={`callout-dot ${doc.status}`}/><div><strong>{doc.note||'Pipeline is progressing through the normal document stages.'}</strong><small>{pipeline?'Live API status':'Stage durations are illustrative mock data.'}</small></div></div><div className="timeline">{stages.map((s:any,i:number)=><div className="timeline-row" key={s.name}><div className={`timeline-marker ${s.state}`}>{s.state==='completed'?<CheckCircle2 size={15}/>:s.state==='failed'?<XCircle size={15}/>:s.state==='review'?<AlertTriangle size={15}/>:s.state==='running'?<LoaderCircle size={15}/>:<span/>}</div><div className="timeline-content"><div><strong>{s.name}</strong><span className={`stage-label ${s.state}`}>{s.state==='completed'?'Completed':s.state==='running'?'Running':s.state==='review'?'Review required':s.state==='failed'?'Failed':'Queued'}</span></div><small>{s.detail||'Technical stage status'}</small></div><time>{s.duration}</time>{i===3&&<div className="parallel"><div><b>SKU mapping</b><span>{pipeline?`${pipeline.sku_mapping.completed} of ${pipeline.sku_mapping.total} candidates mapped`:'3 of 4 candidates mapped'}</span></div><div><b>Term enrichment</b><span>{pipeline?.term_applicability?.status||'Running independently'}</span></div></div>}</div>)}</div></div>}
function Result({doc,pipeline}:{doc:MockDocument;pipeline?:Pipeline}){const raw=(pipeline?.normalization?.result as any)?.line_items as any[]|undefined;const items=raw?.map((x:any)=>({name:x.description||x.name||x.source_candidate_id,sku:x.sku_code||x.sku_id||'—',quantity:x.quantity?.amount||x.quantity,currency:x.currency||x.unit_price?.currency,total:x.total_listed_value?.amount||x.total_listed_value,unitPrice:x.unit_price?.amount||x.unit_price,period:x.service_start_date&&x.service_end_date?`${x.service_start_date} – ${x.service_end_date}`:'—',billing:x.invoicing_frequency||'—',payment:x.payment_terms||'—',review:false}))||doc.lineItems;if(!items.length)return <div className="empty-state"><AlertTriangle size={20}/><strong>No normalized output available</strong><span>This document has not produced a final result yet.</span></div>;return <div className="result"><div className="result-heading"><div><h3>Normalized line items</h3><span className="muted">{pipeline?'Persisted API result':'Values shown are sample UI data'}</span></div></div><div className="line-items">{items.map((item:any,i:number)=><div className={`line-item ${item.review?'needs-review':''}`} key={item.sku||i}><div className="item-top"><div><strong>{item.name}</strong><span>{item.sku}</span></div>{item.review&&<span className="review-tag"><AlertTriangle size={13}/>Needs review</span>}</div><div className="item-grid"><span><small>Quantity</small>{item.quantity||'—'}</span><span><small>Currency</small>{item.currency||'—'}</span><span><small>Unit price</small>{item.unitPrice||'—'}</span><span><small>Total</small>{item.total||'—'}</span><span><small>Service period</small>{item.period||'—'}</span><span><small>Billing</small>{item.billing||'—'}</span><span><small>Payment terms</small>{item.payment||'—'}</span></div></div>)}</div></div>}
function Evidence({doc}:{doc:MockDocument}){const evidence=doc.lineItems.flatMap(i=>i.evidence);if(!evidence.length)return <div className="empty-state"><FileText size={20}/><strong>Evidence will appear here</strong><span>Persisted page references populate after analysis.</span></div>;return <div className="evidence-list">{evidence.map(e=><article key={e.id}><div className="evidence-id"><span>PAGE {e.page}</span><code>{e.id}</code><span className="evidence-kind">{e.kind}</span></div><div className="evidence-preview"><div className="page-box"><FileText size={18}/><small>Page {e.page}<br/>region preview</small></div><div><strong>{e.supports}</strong><p>“{e.excerpt}”</p></div></div></article>)}</div>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
