import type { Batch, MockDocument, Evidence } from './types';
const ev=(page:number,id:string,excerpt:string,supports:string,kind:'block'|'table'='block'):Evidence=>({page,id,excerpt,supports,kind});
const stages=(states:string[]):MockDocument['stages']=>['Upload','PDF preprocessing','Document analysis','SKU mapping','Term enrichment','Normalization / finalization'].map((name,i)=>({name,state:states[i] as any,duration:i===0?'—':i<3?'18s':i===3?'42s':'—',detail:i===3?'3 of 4 candidates mapped':i===4?'Running independently':undefined}));
export const batch:Batch={name:'September order forms',documents:[
 {id:'doc-01',filename:'acme-cloud-renewal.pdf',customer:'Acme Corporation',uploaded:'Today, 09:42',status:'processing',stage:'Term enrichment',itemCount:4,pages:5,stages:stages(['completed','completed','completed','completed','running','queued']),lineItems:[],evidence:[],note:'SKU mapping is complete. Term enrichment is still running independently.'},
 {id:'doc-02',filename:'northstar-enterprise-order.pdf',customer:'Northstar Labs',uploaded:'Today, 08:18',status:'completed',stage:'Completed',itemCount:3,pages:4,stages:stages(['completed','completed','completed','completed','completed','completed']),lineItems:[{sku:'MAX-ENT-042',name:'Enterprise Platform',quantity:'250',currency:'USD',unitPrice:'$1,200',total:'$300,000',period:'Annual',billing:'Annual',payment:'Net 30',evidence:[ev(2,'layout:p0002:b000014','Enterprise Platform · 250 seats · $1,200 / year','Supports quantity and unit price','table')]},{sku:'MAX-SUP-010',name:'Priority Support',quantity:'1',currency:'USD',unitPrice:'$24,000',total:'$24,000',period:'Annual',billing:'Annual',payment:'Net 30',evidence:[ev(3,'native:p0003:b000006','Priority Support — annual $24,000','Supports support line total')]},{sku:'MAX-DATA-008',name:'Data retention add-on',quantity:'1',currency:'USD',unitPrice:'$8,400',total:'$8,400',period:'Annual',billing:'Annual',payment:'Net 30',evidence:[ev(3,'table:p0003:t0001','Data retention add-on · $8,400','Supports add-on price','table')]}],evidence:[]},
 {id:'doc-03',filename:'brightline-services.pdf',customer:'Brightline Health',uploaded:'Yesterday, 16:05',status:'review_required',stage:'Normalization / finalization',itemCount:2,pages:3,stages:stages(['completed','completed','completed','completed','completed','review']),lineItems:[{sku:'MAX-OPS-021',name:'Operations Suite',quantity:'—',currency:'USD',unitPrice:'$4,500',total:'—',period:'Monthly',billing:'Monthly',payment:'Net 45',review:true,evidence:[ev(1,'native:p0001:b000003','Operations Suite · monthly fee $4,500','Supports product and unit price')]},{sku:'MAX-IMPL-003',name:'Implementation Services',quantity:'1',currency:'USD',unitPrice:'$12,000',total:'$12,000',period:'One-time',billing:'One-time',payment:'Net 45',evidence:[ev(2,'layout:p0002:b000009','Implementation Services · $12,000 one-time','Supports implementation fee')]}],evidence:[],note:'Quantity for Operations Suite needs review; no default was invented.'},
 {id:'doc-04',filename:'vector-industries.pdf',customer:'Vector Industries',uploaded:'Yesterday, 13:22',status:'failed_validation',stage:'Normalization / finalization',itemCount:0,pages:2,stages:stages(['completed','completed','completed','completed','completed','failed']),lineItems:[],evidence:[],note:'Validation stopped on an inconsistent SKU identity.'},
 {id:'doc-05',filename:'meridian-software.pdf',customer:'Meridian Software',uploaded:'Mon, 11:09',status:'completed',stage:'Completed',itemCount:5,pages:7,stages:stages(['completed','completed','completed','completed','completed','completed']),lineItems:[],evidence:[]},
 {id:'doc-06',filename:'summit-public-sector.pdf',customer:'Summit Public Sector',uploaded:'Mon, 09:31',status:'queued',stage:'Queued',itemCount:0,pages:6,stages:stages(['completed','queued','queued','queued','queued','queued']),lineItems:[],evidence:[]}
]};
